KTOS: core/ktos.c File Reference
ktos.c File Reference
KTOS Core — scheduler and task management
KTOS cooperative scheduler implementation.
#include "ktos_multi.h"
#include "ktos.h"
#include "ktos_hal.h"
#include <stdlib.h>
#include <stdbool.h>
Functions
void ktos_timer_irq_handler (void)
1 ms system tick interrupt handler.
static void ktos_SwitchTask (void)
static void ktos_DefaultTaskExitHandler (WORD task_return_value)
Default exit handler called when a task function returns.
struct ktos_TASK * ktos_InitTask (WORD(*Func)(WORD MsgType, WORD sParam, LONG lParam), INT StackSize, INT QueueSize, BYTE TaskIDVal)
void ktos_RunOS (void)
Start the KTOS scheduler. Never returns.
bool ktos_SendMsg (struct ktos_TASK *Task, WORD MsgType, WORD sParam, LONG lParam)
void ktos_WakeUp (struct ktos_TASK *Task, INT WakeUpType)
Wake a sleeping task immediately from an ISR or another task.
static void __attribute__ ((unused))
Round-robin cooperative scheduler — runs on the OS stack.
INT ktos_Sleep (WORD Delay, bool TaskSwitchPermit)
Variables
static struct ktos_TASK * TaskCurrent = NULL
static bool MultiTask = TRUE
static int32_t * OS_SP = NULL
static WORD g_LastTaskReturnValue
Detailed Description
KTOS cooperative scheduler implementation.
This file contains the kernel internals: task initialisation, the round-robin scheduler (ktos_SwitchTask), the 1 ms timer ISR, message queuing, and cooperative sleep/wake. Application code should not call any of the static functions declared here — use the public API in ktos.h.
Warning
Using ktos_Sleep() with TASK_SWITCH_INHIBIT and MSG_WAIT:
When TASK_SWITCH_INHIBIT is passed to ktos_Sleep(), the scheduler focuses exclusively on the current task and will not advance to others. If MSG_WAIT is also passed, the system halts for all other tasks until an ISR calls ktos_WakeUp() on this specific task.
The 1 ms timer ISR (ktos_timer_irq_handler) continues to fire and update task timers, but no other task will be dispatched until this task resumes.
Use only for very short, critical sections where an ISR is guaranteed to call ktos_WakeUp(). Improper use leads to an unresponsive system.
Definition in file ktos.c.
Function Documentation
__attribute__()
static void __attribute__ ((unused)) static
Round-robin cooperative scheduler — runs on the OS stack.
This is the heart of KTOS. It executes in a permanent loop on the OS stack pointer (OS_SP) and is never called directly by application code. ktos_hal_StartScheduler() transfers control here for the first time; ktos_DefaultTaskExitHandler() returns here after each task yields.
Scheduling algorithm
If MultiTask is true, advance TaskCurrent to the next task in the circular ring.
If the task is sleeping but its timer has fired, mark it ready.
If the task is ready (not sleeping and has a message or timer event), context-switch into it.
On return from the task, read g_LastTaskReturnValue and update the task's timer accordingly.
Repeat forever.
Definition at line 229 of file ktos.c.
References FALSE, g_LastTaskReturnValue, ktos_hal_ContextSwitch(), ktos_hal_DisableInterrupts(), ktos_hal_EnableInterrupts(), MSG_WAIT, ktos_TASK::MsgCount, ktos_TASK::MsgQueue, ktos_TASK::MsgQueueEnd, ktos_TASK::MsgQueueOut, MultiTask, OS_SP, ktos_TASK::Sleeping, ktos_TASK::StackPtr, TaskCurrent, ktos_TASK::TaskNext, ktos_TASK::Timer, ktos_TASK::TimerFlag, and TRUE.
ktos_DefaultTaskExitHandler()
static void ktos_DefaultTaskExitHandler (WORD task_return_value) static
Default exit handler called when a task function returns.
Captures the task's return value into g_LastTaskReturnValue, then context-switches back to the OS scheduler (ktos_SwitchTask). The scheduler reads g_LastTaskReturnValue to determine the task's next sleep duration.
Installed automatically by ktos_InitTask() as the task_exit_handler_addr argument to ktos_hal_InitTaskStack(). Application code never calls this.
Parameters
task_return_value The value returned by the task function (sleep duration in ms, or MSG_WAIT).
Definition at line 84 of file ktos.c.
References g_LastTaskReturnValue, ktos_DebugPrintf(), ktos_Emergency(), ktos_hal_ContextSwitch(), OS_SP, ktos_TASK::StackPtr, TaskCurrent, and ktos_TASK::TaskID.
Referenced by ktos_InitTask().
ktos_InitTask()
struct ktos_TASK* ktos_InitTask (WORD(*)(WORD MsgType, WORD sParam, LONG lParam) Func, INT StackSize, INT QueueSize, BYTE TaskIDVal)
Definition at line 108 of file ktos.c.
References FALSE, ktos_TASK::Func, ktos_DefaultTaskExitHandler(), ktos_Emergency(), ktos_hal_InitTaskStack(), KTOS_MSG_TYPE_INIT, ktos_TASK::MsgCount, ktos_TASK::MsgQueue, ktos_TASK::MsgQueueEnd, ktos_TASK::MsgQueueIn, ktos_TASK::MsgQueueOut, ktos_TASK::QueueCapacity, ktos_TASK::Sleeping, ktos_TASK::StackPtr, TaskCurrent, ktos_TASK::TaskID, ktos_TASK::TaskNext, ktos_TASK::Timer, and ktos_TASK::TimerFlag.
Referenced by main().
ktos_SendMsg()
bool ktos_SendMsg (struct ktos_TASK * Task, WORD MsgType, WORD sParam, LONG lParam)
Definition at line 173 of file ktos.c.
References ktos_hal_DisableInterrupts(), ktos_hal_EnableInterrupts(), ktos_MSG::lParam, ktos_TASK::MsgCount, ktos_TASK::MsgQueue, ktos_TASK::MsgQueueEnd, ktos_TASK::MsgQueueIn, ktos_MSG::MsgType, ktos_TASK::QueueCapacity, and ktos_MSG::sParam.
Referenced by main().
ktos_Sleep()
INT ktos_Sleep (WORD Delay, bool TaskSwitchPermit)
Definition at line 286 of file ktos.c.
References ktos_hal_ContextSwitch(), ktos_hal_DisableInterrupts(), ktos_hal_EnableInterrupts(), MSG_WAIT, MultiTask, OS_SP, ktos_TASK::Sleeping, ktos_TASK::StackPtr, TaskCurrent, ktos_TASK::Timer, ktos_TASK::TimerFlag, TRUE, and ktos_TASK::WakeUpType.
ktos_SwitchTask()
static void ktos_SwitchTask (void) static
ktos_timer_irq_handler()
void ktos_timer_irq_handler (void)
1 ms system tick interrupt handler.
Called by the BSP's hardware timer ISR every millisecond. Walks the circular task ring and decrements each task's Timer counter. When a counter reaches zero, TimerFlag is set so the scheduler dispatches the task on the next scheduling cycle.
Note
This function is registered with the BSP via ktos_hal_InitSystemTimer() and must not be called directly from application code.
Definition at line 326 of file ktos.c.
References TaskCurrent, ktos_TASK::TaskNext, ktos_TASK::Timer, ktos_TASK::TimerFlag, and TRUE.
Referenced by ktos_RunOS().
Variable Documentation
g_LastTaskReturnValue
WORD g_LastTaskReturnValue static
Holds the WORD return value of the most recently completed task function. Written by ktos_DefaultTaskExitHandler() before context-switching back to the scheduler; read by ktos_SwitchTask() immediately after the switch.
Definition at line 64 of file ktos.c.
Referenced by __attribute__(), and ktos_DefaultTaskExitHandler().
MultiTask
bool MultiTask = TRUE static
When TRUE the scheduler advances to the next task on each tick. Set to FALSE by ktos_Sleep() with TASK_SWITCH_INHIBIT.
Definition at line 54 of file ktos.c.
Referenced by __attribute__(), and ktos_Sleep().
OS_SP
int32_t* OS_SP = NULL static
OS scheduler stack pointer. Set by ktos_hal_StartScheduler() and used by ktos_SwitchTask() and ktos_DefaultTaskExitHandler() to return to the scheduler context after a task yields.
Definition at line 59 of file ktos.c.
Referenced by __attribute__(), ktos_DefaultTaskExitHandler(), and ktos_Sleep().
TaskCurrent
struct ktos_TASK* TaskCurrent = NULL static
Pointer to the task currently being dispatched (or most recently run).
Definition at line 50 of file ktos.c.
Referenced by __attribute__(), ktos_DefaultTaskExitHandler(), ktos_InitTask(), ktos_RunOS(), ktos_Sleep(), and ktos_timer_irq_handler().