KTOS: KTOS HAL — hardware abstraction layer
KTOS HAL — hardware abstraction layer
Modules
KTOS BSP — AVR (ATmega328P)
KTOS BSP — Xtensa LX106 (ESP8266)
KTOS BSP — ARM Cortex-M (STM32F103, STM32F030)
Functions
void ktos_hal_DisableInterrupts (void)
Disable all maskable interrupts.
void ktos_hal_EnableInterrupts (void)
Re-enable maskable interrupts.
void * ktos_hal_InitTaskStack (void *p_stack_base, unsigned int stack_size_bytes, WORD(*task_func_addr)(WORD, WORD, LONG), void(*task_exit_handler_addr)(WORD), WORD initial_msg_type, WORD initial_sparam, LONG initial_lparam)
Set up the initial stack frame for a new task.
void ktos_hal_ContextSwitch (void **p_current_sp_storage, void *next_sp)
Perform a cooperative context switch between two execution contexts.
void ktos_hal_StartScheduler (void *first_task_sp)
Launch the KTOS scheduler and the first task. Never returns.
void ktos_hal_InitSystemTimer (void(*timer_isr_addr)(void))
Configure and start the 1 ms system tick timer.
Detailed Description
Function Documentation
ktos_hal_ContextSwitch()
void ktos_hal_ContextSwitch (void ** p_current_sp_storage, void * next_sp)
#include <core/ktos_hal.h>
Perform a cooperative context switch between two execution contexts.
Saves the full CPU register set of the current context onto its stack, records the new stack-pointer value into p_current_sp_storage, loads next_sp into the CPU's stack pointer, then restores the register set of the next context and resumes it.
From the C caller's perspective this function appears to return normally; execution actually continues in the next context and only "returns" here when the scheduler switches back to this context later.
Parameters
p_current_sp_storage Address of the variable that holds this context's saved stack pointer (e.g. &TaskCurrent->StackPtr or &OS_SP). Updated on entry.
next_sp Stack pointer value of the context to switch into (from a previous call to ktos_hal_InitTaskStack() or a previous ktos_hal_ContextSwitch()).
Note
Must be implemented in assembly. Interrupts must be disabled by the caller before invoking this function.
Cortex-M3 skeleton
__attribute__((naked)) void ktos_hal_ContextSwitch(
        void **p_current_sp_storage __attribute__((unused)),
        void  *next_sp          __attribute__((unused)))
{
    __asm volatile(
        "push   {r4-r11}          \n"
        "str    sp, [r0]          \n"  // save current SP → *p_current_sp_storage
        "mov    sp, r1            \n"  // load next SP
        "pop    {r4-r11}          \n"
        "bx     lr                \n"
    );
}
Note
On Cortex-M0 you cannot use STR with SP as source. Route SP through a low register first:
"mov    r2, sp            \n"
"str    r2, [r0]          \n"
Perform a cooperative context switch between two execution contexts.
Saves SREG and R0-R31 of the current context onto the current stack, writes the current SP into *p_current_sp_storage, sets SP to next_sp, then restores R0-R31 and SREG of the new context and returns into it.
Note
AVR SP is split across two 8-bit I/O registers (SPL / SPH).
Perform a cooperative context switch between two execution contexts.
Implementation steps:
ENTRY to create a new register window (or disable windowing first).
Save a0-a15, SAR (shift amount register), and PS onto the current stack.
Store current SP into *p_current_sp_storage.
Load next_sp into a1 (Xtensa SP register).
Restore a0-a15, SAR, and PS from the new stack.
RETW (or equivalent) to jump into the new task.
Reference: Xtensa ISA Reference Manual, Chapter 4 — Register Windows.
Definition at line 150 of file ktos_bsp.c.
Referenced by __attribute__(), ktos_DefaultTaskExitHandler(), and ktos_Sleep().
ktos_hal_DisableInterrupts()
void ktos_hal_DisableInterrupts (void)
#include <core/ktos_hal.h>
Disable all maskable interrupts.
Called by the KTOS kernel to protect critical sections (queue updates, task-state changes). Must not be called from within an ISR.
AVR example
void ktos_hal_DisableInterrupts(void) { cli(); }
Cortex-M example
void ktos_hal_DisableInterrupts(void) { __disable_irq(); }
Disable all maskable interrupts.
Definition at line 40 of file ktos_bsp.c.
Referenced by __attribute__(), ktos_SendMsg(), ktos_Sleep(), and ktos_WakeUp().
ktos_hal_EnableInterrupts()
void ktos_hal_EnableInterrupts (void)
#include <core/ktos_hal.h>
Re-enable maskable interrupts.
Paired with ktos_hal_DisableInterrupts(). Every disable must be followed by exactly one enable.
AVR example
void ktos_hal_EnableInterrupts(void) { sei(); }
Cortex-M example
void ktos_hal_EnableInterrupts(void) { __enable_irq(); }
Re-enable maskable interrupts.
Definition at line 43 of file ktos_bsp.c.
Referenced by __attribute__(), ktos_SendMsg(), ktos_Sleep(), and ktos_WakeUp().
ktos_hal_InitSystemTimer()
void ktos_hal_InitSystemTimer (void(*)(void) timer_isr_addr)
#include <core/ktos_hal.h>
Configure and start the 1 ms system tick timer.
Sets up a hardware timer (SysTick, Timer1, FRC1, …) to fire an interrupt exactly every 1 ms and call timer_isr_addr inside that ISR.
The KTOS scheduler relies on this 1 ms resolution to track task timers and sleep durations accurately.
Parameters
timer_isr_addr Pointer to ktos_timer_irq_handler() from ktos.c. The BSP must call this function from within its timer ISR.
AVR Timer1 CTC example (16 MHz, prescaler 64, OCR1A = 249)
void ktos_hal_InitSystemTimer(void (*isr)(void))
{
    g_ktos_timer_isr = isr;
    TCCR1A = 0;
    TCCR1B = (1 << WGM12) | (1 << CS11) | (1 << CS10); // CTC, prescaler 64
    OCR1A  = 249;                                         // 1 ms at 16 MHz
    TIMSK1 = (1 << OCIE1A);
}
// ISR calls g_ktos_timer_isr() directly.
Cortex-M SysTick example (72 MHz)
void ktos_hal_InitSystemTimer(void (*isr)(void))
{
    g_ktos_timer_isr = isr;
    SysTick_Config(72000); // 72 MHz / 72000 = 1 kHz
}
void SysTick_Handler(void) { g_ktos_timer_isr(); }
Configure and start the 1 ms system tick timer.
Settings: prescaler 64, OCR1A = 249 → 1 ms at 16 MHz. The ISR vector TIMER1_COMPA_vect must be defined in the application and must call ktos_timer_irq_handler().
Configure and start the 1 ms system tick timer.
Uses prescaler 256: 80 MHz / 256 / 1000 ≈ 312 ticks per ms. Register the ISR manually after calling this function:
ETS_FRC_TIMER1_INTR_ATTACH(ktos_timer_irq_handler, NULL);
ETS_FRC1_INTR_ENABLE();
Configure and start the 1 ms system tick timer.
Definition at line 57 of file ktos_bsp.c.
References FRC1_CTRL_ADDRESS, FRC1_CTRL_DIV_256, FRC1_CTRL_INT_EN, FRC1_CTRL_RELOAD, FRC1_LOAD_ADDRESS, FRC1_TICKS_PER_MS, SYSTICK_CTRL, SYSTICK_CTRL_CLKSOURCE, SYSTICK_CTRL_ENABLE, SYSTICK_CTRL_TICKINT, SYSTICK_LOAD, and SYSTICK_VAL.
Referenced by ktos_RunOS().
ktos_hal_InitTaskStack()
void* ktos_hal_InitTaskStack (void * p_stack_base, unsigned int stack_size_bytes, WORD(*)(WORD, WORD, LONG) task_func_addr, void(*)(WORD) task_exit_handler_addr, WORD initial_msg_type, WORD initial_sparam, LONG initial_lparam)
#include <core/ktos_hal.h>
Set up the initial stack frame for a new task.
This function crafts a fake "saved context" at the top of the task's stack so that when ktos_hal_ContextSwitch() first switches to this task it begins execution at task_func_addr with the three initial parameters.
When task_func_addr returns, execution must transfer to task_exit_handler_addr with the task's return value (a WORD) as the sole argument. The exit handler performs the final context switch back to the OS scheduler.
Parameters
p_stack_base Pointer to the start (lowest address) of the allocated stack buffer.
stack_size_bytes Size of that buffer in bytes.
task_func_addr Entry point of the task function.
task_exit_handler_addr Called when the task function returns; receives the task's WORD return value.
initial_msg_type MsgType passed to the task on first dispatch (always KTOS_MSG_TYPE_INIT on startup).
initial_sparam sParam for the first dispatch.
initial_lparam lParam for the first dispatch.
Returns
The initial stack pointer value to store in Task->StackPtr. Returns NULL if the stack is too small for the frame.
Note
The stack layout is architecture-specific. Study an existing BSP (e.g. bsp/stm32f103/ktos_bsp.c) before writing a new one.
Set up the initial stack frame for a new task.
AVR stack grows downward. The frame looks exactly like what would be left on the stack after the task function called a subroutine, so that ktos_hal_ContextSwitch() can restore it uniformly.
Stack layout (top = lowest address):
[ R31..R1, R0 ]  32 general-purpose registers (R0 last, SREG first)
[ SREG ]         status register (bit 7 = I, interrupts enabled)
[ exit PC high ] return address of exit handler (AVR pushes PC as 2 bytes)
[ exit PC low  ]
[ task PC high ] entry point of the task function
[ task PC low  ]
Set up the initial stack frame for a new task.
Identical layout to the Cortex-M3 BSP. Both cores share the same exception frame format (xPSR, PC, LR, R12, R3, R2, R1, R0) and the KTOS software-saved R4-R11 block.
Set up the initial stack frame for a new task.
Cortex-M hardware automatically pushes/pops R0-R3, R12, LR, PC, xPSR on exceptions. KTOS manually saves/restores R4-R11. The synthesised frame:
(low address / top of stack)
  R4-R11   (zeroed)      ← software-saved, restored by ContextSwitch
  R0       (MsgType)     ← first task argument
  R1       (sParam)
  R2       (lParam low)
  R3       (lParam high)
  R12      (0)
  LR       (exit handler)
  PC       (task entry)
  xPSR     (0x01000000) ← Thumb bit set
(high address / bottom of stack)
Definition at line 94 of file ktos_bsp.c.
Referenced by ktos_InitTask().
ktos_hal_StartScheduler()
void ktos_hal_StartScheduler (void * first_task_sp)
#include <core/ktos_hal.h>
Launch the KTOS scheduler and the first task. Never returns.
Called once by ktos_RunOS() after all tasks have been initialised. The implementation must:
Store the current OS stack pointer into the kernel's OS_SP variable so the scheduler can return to it later via ktos_hal_ContextSwitch().
Load first_task_sp into the CPU stack pointer and restore the task's initial register context (as laid out by ktos_hal_InitTaskStack()).
Enable interrupts and begin executing the first task.
Parameters
first_task_sp Initial stack pointer of the first task to run (the value returned by ktos_hal_InitTaskStack()).
Note
Must be implemented in assembly. This function must not return.
Launch the KTOS scheduler and the first task. Never returns.
Sets the AVR stack pointer to first_task_sp, restores the initial register context built by ktos_hal_InitTaskStack(), and executes RET to jump to the task entry point.
Launch the KTOS scheduler and the first task. Never returns.
Must set a1 (SP) to first_task_sp, restore the initial register context, and jump to the task entry point without returning.
Definition at line 259 of file ktos_bsp.c.
Referenced by ktos_RunOS().