KTOS: KTOS Core — scheduler and task management
KTOS Core — scheduler and task management
Files
file ktos.c
KTOS cooperative scheduler implementation.
Macros
#define TASK_SWITCH_PERMIT 1
Pass to ktos_Sleep() to allow the scheduler to run other tasks while this task is sleeping.
#define TASK_SWITCH_INHIBIT 0
Pass to ktos_Sleep() to prevent the scheduler from running any other task while this task is sleeping.
#define MSG_WAIT 0xffff
Return this value from a task function to sleep indefinitely until explicitly woken by ktos_WakeUp() or an incoming message.
Functions
struct ktos_TASK * ktos_InitTask (unsigned short int(*Func)(unsigned short int MsgType, unsigned short int sParam, long lParam), INT StackSize, INT QueueSize, BYTE TaskID)
Create and register a new task with the KTOS scheduler.
void ktos_RunOS (void)
Start the KTOS scheduler. Never returns.
bool ktos_SendMsg (struct ktos_TASK *Task, unsigned short int MsgType, unsigned short int sParam, long lParam)
Enqueue a message for delivery to a task.
int ktos_Sleep (unsigned short int Delay, bool TaskSwitchPermit)
Yield the CPU for a given duration and optionally allow other tasks to run.
void ktos_WakeUp (struct ktos_TASK *Task, INT WakeUpType)
Wake a sleeping task immediately from an ISR or another task.
void ktos_Emergency (const char *Msg)
Emit a fatal-error message and halt execution.
void ktos_DebugPrintf (const char *Format,...)
Printf-style debug logging (active only when DEBUG == 1).
void ktos_InitSys (void)
Optional platform-level system initialisation hook.
Detailed Description
Macro Definition Documentation
MSG_WAIT
#define MSG_WAIT 0xffff
#include <core/ktos.h>
Return this value from a task function to sleep indefinitely until explicitly woken by ktos_WakeUp() or an incoming message.
Definition at line 77 of file ktos.h.
TASK_SWITCH_INHIBIT
#define TASK_SWITCH_INHIBIT 0
#include <core/ktos.h>
Pass to ktos_Sleep() to prevent the scheduler from running any other task while this task is sleeping.
Warning
Combining with MSG_WAIT as the delay causes the entire system to halt until an ISR calls ktos_WakeUp() on this task. Use with extreme caution and only for very short, critical sections.
Definition at line 70 of file ktos.h.
TASK_SWITCH_PERMIT
#define TASK_SWITCH_PERMIT 1
#include <core/ktos.h>
Pass to ktos_Sleep() to allow the scheduler to run other tasks while this task is sleeping.
This is the normal mode — the task sleeps and the scheduler advances to the next ready task.
Definition at line 59 of file ktos.h.
Function Documentation
ktos_DebugPrintf()
void ktos_DebugPrintf (const char * Format, ...)
#include <core/ktos_multi.h>
Printf-style debug logging (active only when DEBUG == 1).
The BSP or application must provide an implementation that routes output to a UART or semihosting channel. When DEBUG == 0 the calls are compiled out by the kernel and this function is never called.
Parameters
Format printf-compatible format string.
... Variadic arguments matching the format string.
Definition at line 18 of file ktos_multi.c.
Referenced by ktos_DefaultTaskExitHandler().
ktos_Emergency()
void ktos_Emergency (const char * Msg)
#include <core/ktos_multi.h>
Emit a fatal-error message and halt execution.
Called by the kernel whenever an unrecoverable condition occurs (e.g. memory allocation failure). The BSP or application must provide an implementation that outputs Msg via a debug channel (UART, ITM, …) and then enters an infinite loop or triggers a watchdog reset.
Parameters
Msg Short, null-terminated error string (ASCII).
Note
This function must never return.
Definition at line 12 of file ktos_multi.c.
Referenced by ktos_DefaultTaskExitHandler(), ktos_InitTask(), ktos_RunOS(), and main().
ktos_InitSys()
void ktos_InitSys (void)
#include <core/ktos_multi.h>
Optional platform-level system initialisation hook.
Called by application code before ktos_InitTask() if low-level hardware setup (clock configuration, watchdog disable, …) is needed. May be a no-op on platforms where the BSP Makefile startup file handles all initialisation.
Definition at line 22 of file ktos_multi.c.
Referenced by ktos_TaskMainProc().
ktos_InitTask()
struct ktos_TASK* ktos_InitTask (unsigned short int(*)(unsigned short int MsgType, unsigned short int sParam, long lParam) Func, INT StackSize, INT QueueSize, BYTE TaskID)
#include <core/ktos.h>
Create and register a new task with the KTOS scheduler.
Allocates a task control block and stack, initialises the task's message queue, and inserts the task into the circular scheduling ring. Call this for every task before calling ktos_RunOS().
Parameters
Func Pointer to the task function. Signature:
WORD task(WORD MsgType, WORD sParam, LONG lParam);
Return value is the sleep duration in milliseconds, or MSG_WAIT to sleep until explicitly woken.
StackSize Stack depth in 32-bit words (not bytes). Must be large enough for the deepest call chain, all local variables, and interrupt frame overhead. Start with TASK_MAIN_STACK_SIZE (512 words) and reduce if RAM is tight.
QueueSize Maximum number of messages the task can queue at once. Messages sent to a full queue are silently dropped. TASK_MAIN_QUEUE_SIZE (3) is a safe default.
TaskID Single-byte identifier for debug output (e.g. 'M' for main task, 'S' for sensor task).
Returns
Pointer to the newly created task control block. Pass this to ktos_SendMsg() and ktos_WakeUp().
Note
ktos_Emergency() is called and execution halts if any allocation fails.
Example
struct ktos_TASK *sensor = ktos_InitTask(sensor_task, 256, 4, 'S');
struct ktos_TASK *led    = ktos_InitTask(led_task,    128, 2, 'L');
ktos_RunOS();
ktos_RunOS()
void ktos_RunOS (void)
#include <core/ktos.h>
Start the KTOS scheduler. Never returns.
Initialises the 1 ms system tick timer and transfers control to the first registered task. All tasks must be created with ktos_InitTask() before calling this function.
Note
If called with no tasks registered, ktos_Emergency() is invoked.
ktos_InitTask(my_task, TASK_MAIN_STACK_SIZE, TASK_MAIN_QUEUE_SIZE, 'M');
ktos_RunOS(); // execution never reaches here
Definition at line 161 of file ktos.c.
References ktos_Emergency(), ktos_hal_InitSystemTimer(), ktos_hal_StartScheduler(), ktos_timer_irq_handler(), ktos_TASK::StackPtr, and TaskCurrent.
Referenced by main().
ktos_SendMsg()
bool ktos_SendMsg (struct ktos_TASK * Task, unsigned short int MsgType, unsigned short int sParam, long lParam)
#include <core/ktos.h>
Enqueue a message for delivery to a task.
Thread-safe: interrupts are briefly disabled while writing to the queue. May be called from ISR context.
If the target task's queue is full the message is discarded and false is returned — no assertion or error is raised.
Parameters
Task Target task (returned by ktos_InitTask()).
MsgType Message type identifier (built-in or user-defined WORD).
sParam 16-bit user-defined parameter.
lParam 32-bit user-defined parameter.
Returns
true — message queued successfully.
false — queue full or Task is NULL; message dropped.
Example — notify a task from an ISR
void USART_RX_IRQHandler(void)
{
    uint8_t byte = USART->DR;
    ktos_SendMsg(g_uart_task, MSG_UART_RX, byte, 0);
}
ktos_Sleep()
int ktos_Sleep (unsigned short int Delay, bool TaskSwitchPermit)
#include <core/ktos.h>
Yield the CPU for a given duration and optionally allow other tasks to run.
The task suspends itself for Delay milliseconds. When the timer expires the scheduler delivers KTOS_MSG_TYPE_TIMER on the next invocation. Call from task context only — never from an ISR.
Equivalent to returning Delay directly from the task function; the difference is that ktos_Sleep() can be invoked deep inside a call stack.
Parameters
Delay Sleep duration in milliseconds.
0 — yield immediately (run other tasks once, then resume).
1–65534 — sleep for that many milliseconds.
MSG_WAIT — sleep indefinitely until ktos_WakeUp() is called.
TaskSwitchPermit TASK_SWITCH_PERMIT (1) — allow other tasks to run while sleeping. TASK_SWITCH_INHIBIT (0) — freeze scheduler; only this task can resume (requires ISR to call ktos_WakeUp()).
Returns
The WakeUpType value supplied by the ktos_WakeUp() call that woke this task, or 0 if woken by the timer.
Warning
Passing both MSG_WAIT and TASK_SWITCH_INHIBIT halts all other tasks until an ISR calls ktos_WakeUp(). Use with extreme caution.
Example
// Inside a task function — wait 200 ms then continue
ktos_Sleep(200, TASK_SWITCH_PERMIT);
// Execution resumes here after 200 ms
ktos_WakeUp()
void ktos_WakeUp (struct ktos_TASK * Task, INT WakeUpType)
#include <core/ktos.h>
Wake a sleeping task immediately from an ISR or another task.
Sets the task's TimerFlag so the scheduler will dispatch it on the next scheduling cycle. Safe to call from ISR context.
Has no effect if the task is not currently sleeping.
Parameters
Task Task to wake (returned by ktos_InitTask()).
WakeUpType Arbitrary value returned to the sleeping task by ktos_Sleep(). Use this to communicate why the task was woken (e.g. which peripheral triggered the event).
Example — wake a task from a button ISR
void EXTI0_IRQHandler(void)
{
    ktos_WakeUp(g_ui_task, WAKE_BUTTON_PRESS);
}
// Inside g_ui_task:
int reason = ktos_Sleep(MSG_WAIT, TASK_SWITCH_PERMIT);
if (reason == WAKE_BUTTON_PRESS) { handle_button(); }
Definition at line 195 of file ktos.c.
References ktos_hal_DisableInterrupts(), ktos_hal_EnableInterrupts(), ktos_TASK::Sleeping, ktos_TASK::TimerFlag, TRUE, and ktos_TASK::WakeUpType.