KTOS: core/ktos_multi.c File Reference
ktos_multi.c File Reference
#include "ktos_multi.h"
#include "ktos.h"
#include <stdarg.h>
#include <stdio.h>
Functions
static WORD ktos_TaskMainProc (WORD MsgType, WORD sParam, LONG lParam)
void ktos_Emergency (const char *Msg)
Emit a fatal-error message and halt execution.
void ktos_DebugPrintf (const char *Format,...)
Printf-style debug logging (active only when DEBUG == 1).
void ktos_InitSys (void)
Optional platform-level system initialisation hook.
int main ()
Variables
struct ktos_TASK * TaskMain
struct ktos_TASK * TaskSerial
struct ktos_TASK * TaskCheckSum
Function Documentation
ktos_TaskMainProc()
static WORD ktos_TaskMainProc (WORD MsgType, WORD sParam, LONG lParam) static
Definition at line 40 of file ktos_multi.c.
References ktos_InitSys(), KTOS_MSG_TYPE_INIT, KTOS_MSG_TYPE_SYSTEM_START, and MSG_WAIT.
Referenced by main().
main()
int main ()
Definition at line 25 of file ktos_multi.c.
References ktos_Emergency(), ktos_InitTask(), KTOS_MSG_TYPE_INIT, ktos_RunOS(), ktos_SendMsg(), ktos_TaskMainProc(), TASK_MAIN_ID, TASK_MAIN_QUEUE_SIZE, TASK_MAIN_STACK_SIZE, and TaskMain.
Variable Documentation
TaskCheckSum
struct ktos_TASK* TaskCheckSum
TaskMain
struct ktos_TASK* TaskMain
Definition at line 8 of file ktos_multi.c.
Referenced by main().
TaskSerial
struct ktos_TASK* TaskSerial